Blog/urls.py
from django.urls import URLPattern, path
from . import views



urlpatterns =[
    path('',views.home,name='home'),
    path('contact',views.contact,name='contact'),
    path('userhome',views.userhome,name='userhome'),
    path('addpost/<int:id>',views.addpost,name='addpost'),
    path('editprofile/<int:id>',views.editprofile,name="editprofile"),
    path('update/<int:id>',views.update,name='update'),
    path('doc',views.doc,name='doc'),
]

Blog_Post/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
    path('user/',include('django.contrib.auth.urls')),
      
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from email.policy import default
from pyexpat import model
from time import timezone
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class User(AbstractUser):
    contactno=models.CharField(max_length=10,unique=True,null=True)
    twitter_api_key=models.CharField(max_length=255,null=True)
    twitter_api_key_secret=models.CharField(max_length=255,null=True)
    twitter_access_token=models.CharField(max_length=255,null=True)
    twitter_access_token_secret=models.CharField(max_length=255,null=True)
    insta_username=models.CharField(max_length=255,null=True)
    insta_password=models.CharField(max_length=255,null=True)
    facebook_access_token=models.CharField(max_length=255,null=True)
    def __str__(self):
        return self.username
    
class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    content=models.TextField()
    image=models.ImageField()
    is_twitter=models.BooleanField('Twitter',default=False)
    is_facebook=models.BooleanField('Facebook',default=False)
    is_instagram=models.BooleanField('Instagram',default=False)
    created_date=models.DateTimeField(default=timezone.now)
    
    @property
    def imageurl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url 

    class Meta:
        ordering=('created_date',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('userhome')



templates/addpost.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

   
  </head>
  <body>
    <div class="container">
        <h1>Add Post...</h1>
        <div class="form-group">
            <form method="POST" id="form_add" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy }}
                <button id="postbutton" class="btn btn-secondary">Post</button>
            </form>
        </div>
    </div>
   
    <!-- {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %} -->
    <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>    
    {% for message in messages %}
    <script>
      
      // swal('{{message}}')
      swal({
            title: "{{message}}",
            text: "You clicked the button!",
            icon: "warning",
            button: "OK",
          });
    </script>
    {% endfor %}
  
   
  </body>
  
</html>

templates/contact.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.3.1/css/all.css'>
     <!-- Template Main CSS File -->
     <link rel="stylesheet" type="text/css" href="{% static 'contact.css' %}">
   
  </head>
  <body>
   
  <!-- ======= Navigation Bar ======= -->
 
  <nav class="navbar navbar-expand-lg fixed-top  bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">BLOG SPOT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>
          <li class="nav-item">
            <a id="signuplink" data-toggle="modal" data-target="#signupModal" class="nav-link"  href="">Sign Up</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<!-- Navigation Bar -->

 <!--CONTACT SECTION STRATS-->
<section>
  <div id="contactcontainer" class="container py-lg-5 py-md-4 py-2">
    <h3  id="contactheading" class="title-style text-center mb-lg-5 mb-4">Contact <span>Us</span></h3>
    <div class="row text-center mb-5 pb-lg-5 pb-sm-4">
      <div class="col-lg-3 col-sm-6 contact-info">
        <i id="contactlink" class="fas fa-map-marked-alt"></i>
        <h4>Location</h4>
        <p>Kerala, 235 Terry, 10001</p>
      </div>
      <div class="col-lg-3 col-sm-6 contact-info mt-md-0 mt-4">
        <i  id="contactlink" class="fas fa-headset"></i>
        <h4>Phone</h4>
        <p><a href="tel:+44 987 654 321">+44 123 984 439</a></p>
      </div>
      <div class="col-lg-3 col-sm-6 contact-info mt-lg-0 mt-4">
        <i id="contactlink" class="fas fa-envelope-open-text"></i>
        <h4>Email</h4>
        <p><a href="mailto:mail@example.com" class="email">mail@example.com</a></p>
      </div>
      <div class="col-lg-3 col-sm-6 contact-info mt-lg-0 mt-4">
        <i id="contactlink" class="fas fa-user-clock"></i>
        <h4>Working Hours</h4>
        <p>Mon-Sat: 9hrs & Sun: Closed</p>
      </div>
    </div>
    <div id="formdiv" class="form-inner-cont mx-auto" style="max-width:800px">
      <form action="https://sendmail.w3layouts.com/submitForm" method="post" class="signin-form">
        <div class="row align-form-map">
          <div class="col-sm-6 form-input">
            <input type="text"  class="form-control" name="w3lName" id="w3lName" placeholder="Name" />
          </div>
          <div class="col-sm-6 form-input">
            <input type="email" class="form-control" name="w3lSender" id="w3lSender" placeholder="Email" required="" />
          </div>
          <div class="col-sm-6 form-input">
            <input type="text" class="form-control" name="w3lSubect" placeholder="Subject" class="contact-input">
          </div>
          <div class="col-sm-6 form-input">
            <input type="number" class="form-control" name="w3lPhone" placeholder="Phone Number" class="contact-input">
          </div>
          </div>
          <div class="form-input">
            <textarea placeholder="Message" class="form-control" name="w3lMessage" id="w3lMessage" required=""></textarea>
          </div>
          <div id="button" class="submit text-right">
            <button id="submitbutton" type="submit">Submit Message</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

<!--CONTACT SECTION ENDS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
  </body>
</html>

templates/doc.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'doc.css' %}">
   
  </head>
  <body>
    <!--Navigation Bar Starts-->
   <nav class="navbar navbar-expand-lg fixed-top bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color:black;font-size:35px;font-weight: bold;">BLOG SPOT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'doc' %}">Docs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="editprofile/{{user.id}}">Edit Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">{{user.username}}</a>
            </li>
          </ul>
        </div>
    </div>
  </nav>
<!--Navigation Bar Ends-->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/editprofile.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    
  </head>
  <body>
    <div class="container">
        <h1>Edit Profile
            {{user.id}}
        </h1>
        <div class="form-group">
            <form method="POST" action="/update/{{user.id}}" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-6">
                <label for="email" class="form-label" >Email</label>
                <input type="email" class="form-control" name="txtemail" value="{{user.email}}">
                </div>   
            </div>
            <div class="row">
                <div class="col-md-6">
                <label for="contactno" class="form-label" >Contact No</label>
                <input type="text" name="txtcontactno" class="form-control" value="{{user.contactno}}">
                </div> 
            </div>

            <div class="row">
                <div class="col-md-6">
                <label for="username" class="form-label" >Username</label>
                <input type="text" name="txtusername" class="form-control" value="{{user.username}}">
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-6">
                <label for="apikey" class="form-label" >API Key</label>
                <input type="text" name="txtapikey" class="form-control" value="{{user.twitter_api_key}}">
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                <label for="apikeysecret" class="form-label" >API Key Secret</label>
                <input type="text" name="txtapikeysecret" class="form-control" value="{{user.twitter_api_key_secret}}">
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                <label for="accesstoken" class="form-label" >Access Token</label>
                <input type="text" name="txtaccesstoken" class="form-control" value="{{user.twitter_access_token}}">
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                <label for="accesstokensecret" class="form-label" >Access Token Secret</label>
                <input type="text" name="txtaccesstokensecret" class="form-control" value="{{user.twitter_access_token_secret}}">
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                <label for="instausername" class="form-label" >Instagram Username</label>
                <input type="text" name="txtinstausername" class="form-control" value="{{user.insta_username}}">
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                <label for="instapassword" class="form-label" >Instagram Password</label>
                <input type="text" name="txtinstapassword" class="form-control" value="{{user.insta_password}}">
                </div>  
            </div>

            <div class="row">
                <div class="col-md-6">
                <label for="facebookaccess" class="form-label" >Faceook Access Token</label>
                <input type="text" name="txtfacebookaccess" class="form-control" value="{{user.facebook_access_token}}">
                </div>
            </div>

            
            <button class="btn btn-secondary">Save</button>
            </form>
        </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

   
    
  </body>
</html>

templates/home.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.3.1/css/all.css'>
 
  <!-- Template Main CSS File -->
  <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
  

</head>

<body>

<!-- ======= Navigation Bar ======= -->
 
<nav class="navbar navbar-expand-lg fixed-top  bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BLOG SPOT</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>
          <li class="nav-item">
            <a id="signuplink" data-toggle="modal" data-target="#signupModal" class="nav-link"  href="">Sign Up</a>
          </li>
        </ul>
      </div>
  </div>
</nav>
<!-- Navigation Bar -->
<!--Message Display Starts-->
{% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Hey!</strong>{{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %} 
<!--Message Display Starts-->
<!-- ======= Hero Section ======= -->
<section id="hero">
  <div class="container">
    <div class="row d-flex align-items-center">
      <div class=" col-lg-6 py-5 py-lg-0 order-2 order-lg-1" data-aos="fade-right">
        <h1>Your new digital experience with Blog Spot</h1>
        <h2>We are provide a platform to post your blog into multiple platform</h2>
        <a  class="btn-get-started scrollto" data-toggle="modal" data-target="#loginModal" href="{% url 'login'%}">Log in</a>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left">
        <img src="{% static 'images/hero-img.png' %}" class="img-fluid" alt="">
      </div>
    </div>
  </div>
</section><!-- End Hero -->

<!--About Page starts-->
  
  <div class="container" id="about">
    <h1 id="abouth3">About Us</h1>
    <p>This platform for posting users blogs into diffrent social medias. We can see that if a user can post blog to any social media patform,they should have login their account on corrresponding that social media.This is very difficult.Because if a user can post their blogs into diffrent plateform at a time,they should login with the corresponding social media. So,'Post to Multiple Platform' is a solution to overcome this.A user can post their blogs into diffrent social medias at a time with the help of this platform. Meanwhile,user can update and delete their post.
	  </p>
  </div>

<!--About Page Ends-->

<!--Login Starts-->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span id="modalclose" aria-hidden="true">×</span> 
        </button>
      </div>
      <div class="modal-body">
        <div class="form-title text-center">
          <h4>Login</h4>
        </div>
        <div class="d-flex flex-column text-center">
          <form method="POST" action="">
            
            
            {% csrf_token %}
            {{ loginform|crispy }}
            <div id="divloginbutton" class="form-group">
              <button type="submit" style="width:240px;background-color: crimson;margin-left: 50px;" id="loginsubmit" style="margin-top: 10px;background-color: crimson;" class="form-control">Login</button>
            </div>
            <div id="divquestion" class="form-group" style="margin-top: 15px;">
              <h6>You have no account?</h6><a href="" data-toggle="modal" data-target="#signupModal" style="color: red;">signup here</a>
            </div>
          
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Sign Up Starts-->

<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span id="modalclose" aria-hidden="true">×</span> 
          </button>
        </div>
        <div class="modal-body">
          <div class="form-title text-center">
            <h4>Sign Up</h4>
          </div>
          <div class="d-flex flex-column text-center">
            <form id="form" action="" method="POST" autocomplete="off">
              {% csrf_token %}
              {{ signupform|crispy }}
              
              <div id="divbutton" class="form-group">
                <button type="submit" id="submit" style="width: 200px;margin-left: 60px;" class="form-control">Sign Up</button>
              </div>
            </form>
            <div class="text-center text-muted delimiter">or use a social network</div>
            <div class="d-flex justify-content-center social-buttons">
              <button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Twitter">
                <i class="fab fa-twitter"></i>
              </button>
              <button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Facebook">
                <i class="fab fa-facebook"></i>
              </button>
              <button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Linkedin">
               <i class="fab fa-linkedin"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!--Sign Up Ends-->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
    <!-- Popper JS -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'></script>
    <!-- Bootstrap JS -->
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'></script>
    <script type="text/javascript" src="{% static 'signupvalidation.js' %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>    
    {% for message in messages %}
    <script>
      // swal('{{message}}')
      swal({
            title: "{{message}}",
            text: "You clicked the button!",
            icon: "success",
            button: "OK",
          });
    </script>
    {% endfor %}
  <style>
    #id_first_name,#id_last_name,#id_contactno,#id_email,#id_username,#id_password1,#id_password2,#id_password
    {
      width:250px;
    }
  </style> 
</body>
</html>

templates/userhome.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'userhome.css' %}">
  
  </head>
  <body>
   <!--Navigation Bar Starts-->
   <nav class="navbar navbar-expand-lg fixed-top bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color:black;font-size:35px;font-weight: bold;">BLOG SPOT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            <!-- <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'doc' %}">Docs</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="editprofile/{{user.id}}">Edit Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">{{user.username}}</a>
            </li>
          </ul>
        </div>
    </div>
  </nav>
  <!-- <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" style="color:black;font-size:35px;font-weight: bold;" href="#">BLOG SPOT</a>
      <a href="">Docs</a>
      <a href="editprofile/{{user.id}}">Edit Profile</a>
      <a href="{% url 'home' %}">Logout {{user.username}}</a>
    </div>
    
  </nav> -->
   <!--Navigation Bar Ends-->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center" style="height: 100vh;">
  <div class="container" style="padding-top: 0px;">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200" style="padding-top: 0px;">
        <h1>Better Solutions For Your Business</h1>
        <h2>We are team of talented designers making websites with Bootstrap</h2>
        <div class="d-flex justify-content-center justify-content-lg-start" style="padding-top: 0px;">
          <a href="/addpost/{{user.id}}" class="btn-get-started scrollto" style="height: 50px;width: 160px;">Get Started</a>
          <!-- <a href="{% url 'home' %}" id="back" style="width:120px;text-align: center;height: 50px;">Back</a> -->
          <a href="https://www.youtube.com/watch?v=-4Wl2fHHAVs" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>First Watch this Video Before Starting</span></a>
        </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img id="userhomeimg" src="{% static 'images/userhome.png' %}"  class="img-fluid animated" alt="">
      </div>
    </div>
  </div>
</section><!-- End Hero -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <!--Edit Profile-->

</body>
</html>